# site_name: PyEGRO Documentation
# site_url: https://your-username.github.io/PyEGRO/
# repo_url: https://github.com/your-username/PyEGRO.git

# theme:
#   name: material
#   logo: assets/logo.png
#   favicon: assets/favicon.png
#   palette:
#     - media: "(prefers-color-scheme: light)"
#       scheme: default
#       primary: white
#       accent: indigo
#       toggle:
#         icon: material/brightness-7
#         name: Switch to dark mode
#     - media: "(prefers-color-scheme: dark)"
#       scheme: slate
#       primary: white
#       accent: indigo
#       toggle:
#         icon: material/brightness-4
#         name: Switch to light mode
#   features:
#     - navigation.tabs
#     - navigation.sections
#     - navigation.expand
#     - toc.integrate
#     - navigation.top
#     - search.suggest
#     - search.highlight
#     - content.tabs.link
#   language: en
#   icon:
#     repo: fontawesome/brands/github

# # Add this for left alignment
# extra_css:
#   - stylesheets/extra.css

# markdown_extensions:
#   - pymdownx.highlight:
#       anchor_linenums: true
#   - pymdownx.inlinehilite
#   - pymdownx.snippets
#   - pymdownx.superfences
#   - attr_list
#   - md_in_html

# extra:
#   social:
#     - icon: fontawesome/brands/github
#       link: https://github.com/twanglom/pyegro
#     - icon: fontawesome/brands/python
#       link: https://pypi.org/project/pyegro/

# nav:
#   - Home: index.md
#   - Getting Started:
#       - Installation: getting-started/installation.md
#       - Quick Start: getting-started/quickstart.md
#   - User Guide:
#       - Design of Experiment: user-guide/doe.md
#       - Efficient Global Optimization: user-guide/ego.md
#       - Surrogate Modeling: user-guide/meta.md
#       - Robust Optimization: user-guide/robustopt.md
#       - Sensitivity Analysis: user-guide/sensitivity.md
#       - Uncertainty Quantification: user-guide/uq.md
#   - Application Examples:
#       - Overview: examples/overview.md
#       - DOE Examples: examples/doe-examples.md
#       - EGO Examples: examples/ego-examples.md
#   - API Reference: api-reference.md





site_name: PyEGRO Documentation
site_url: https://your-username.github.io/PyEGRO/
repo_url: https://github.com/your-username/PyEGRO.git

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: light-blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: light-blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.indexes
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - navigation.instant # Enables instant loading
    - navigation.collapse
    - navigation.tracking # Enables viewport tracking
  language: en
  icon:
    repo: fontawesome/brands/github

# Include your custom JavaScript
extra_javascript:
  - scripts/custom-nav.js ## for drop dow manu format
  - scripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Add this for left alignment
extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true

plugins:
  - search
  - awesome-pages

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/twanglom/PyEGRO
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/PyEGRO/

nav:
  - Home: index.md
  - Getting Started:
      - Installation: getting-started/installation.md
      - Quick Start: getting-started/quickstart.md
  - User Guide:
      - Design of Experiment:
          - Overview: user-guide/doe/overviewdoe.md
          - Usage: user-guide/doe/usagedoe.md
      - Efficient Global Optimization:
          - Overview: user-guide/ego/overviewego.md
          - Usage: user-guide/ego/usageego.md
      - Surrogate Modeling:
          - Overview: user-guide/meta/overviewmeta.md
          - Usage: user-guide/meta/usagemeta.md
      - Robust Optimization:
          - Overview: user-guide/robustopt/overviewrobust.md
          - Usage: user-guide/robustopt/usagerobust.md
      - Sensitivity Analysis:
          - Overview: user-guide/sensitivity/overviewsensitivity.md
          - Usage: user-guide/sensitivity/usagesensitivity.md
      - Uncertainty Quantification:
          - Overview: user-guide/uq/overviewuq.md
          - Usage: user-guide/uq/usageuq.md
  - Application Examples:
      - Overview: examples/overview.md
      - DOE Examples: examples/doe-examples.md
      - EGO Examples: examples/ego-examples.md
  - API Reference: api-reference.md
