site_name: PyEGRO Documentation
site_url: https://twanglom.github.io/PyEGRO/
repo_url: https://github.com/twanglom/PyEGRO.git

theme: 
  name: readthedocs
  logo: assets/logo.png


# JavaScript for math rendering - this is the key part for math support
extra_javascript:
  - scripts/mathjax.js  # Custom configuration file
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Stylesheets for custom styling
extra_css:
  - stylesheets/extra.css

# Required extensions for math and code highlighting
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true  # This is essential for MathJax 3
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 3

# Rest of your configuration...
plugins:
  - search
  - awesome-pages


nav:
  - Home: index.md
  - Getting Started:
      - Installation: getting-started/installation.md
      - Quick Start: getting-started/quickstart.md
  - Basic Usage:
      - Design of Experiment: basic-usage/doe/doe_examples.md
      - Metamodeling:
          - GPR: basic-usage/meta/gpr/gpr_examples.md
          - Cokriging: basic-usage/meta/cokriging/cokriging_examples.md
          - EGO-GPR: basic-usage/meta/ego-gpr/egogpr_examples.md
          - EGO-Cokriging: basic-usage/meta/ego-cokriging/egocokriging_examples.md          
          - Model Evaluation: basic-usage/meta/model-evalulation/modeltesting_examples.md
      - Robust Optimization:
          - MCS Approach: basic-usage/robustopt/approach-mcs/robustopt_mcs_examples.md
          - PCE Approach: basic-usage/robustopt/approach-pce/robustopt_pce_examples.md
          - NNMCS Approach: basic-usage/robustopt/approach-nnmcs/robustopt_nnmcs_examples.md
      - Sensitivity Analysis:
          - MCS Approach: basic-usage/sensitivity/approach-mcs/samcs_examples.md
          - PCE Approach: basic-usage/sensitivity/approach-pce/sapce_examples.md
      - Uncertainty Quantification:
          - MCS Approach: basic-usage/uncertainty/approach-mcs/uqmcs_examples.md
  - Application Examples:
      - Sensitivity Analysis:
          - Benchmarks: examples/sensitivity-analysis-benchmarks/using-analytical-function.md
          - Benchmarks (using metamodel): examples/sensitivity-analysis-benchmarks/using-metamodel.md
      - Metamodel Training via EGO: examples/ego-metamodel-examples.md
      - Uncertainty Propagation: examples/uq-examples.md
      - Robust Optimization: examples/robust-example.md
  - API Reference:
      - Design of Experiment: api-reference/doe/doe_api_reference.md
      - Metamodeling:
          - GPR: api-reference/meta/gpr/gpr_api_reference.md
          - Cokriging: api-reference/meta/cokriging/cokriging_api_reference.md
          - EGO-GPR: api-reference/meta/ego-gpr/egogpr_api_reference.md
          - EGO-Cokriging: api-reference/meta/ego-cokriging/egocokriging_api_reference.md         
          - Model Evaluation: api-reference/meta/model-evalulation/modeltesting_api_reference.md
      - Robust Optimization:
          - MCS Approach: api-reference/robustopt/approach-mcs/robustopt_mcs_api_reference.md
          - PCE Approach: api-reference/robustopt/approach-pce/robustopt_pce_api_reference.md
          - NNMCS Approach: api-reference/robustopt/approach-nnmcs/robustopt_nnmcs_api_reference.md
      - Sensitivity Analysis:
          - MCS Approach: api-reference/sensitivity/approach-mcs/samcs_api_reference.md
          - PCE Approach: api-reference/sensitivity/approach-pce/sapce_api_reference.md
      - Uncertainty Quantification:
          - MCS Approach: api-reference/uncertainty/approach-mcs/uqmcs_api_reference.md