site_name: PyEGRO Documentation
site_url: https://twanglom.github.io/PyEGRO/
docs_dir: docs

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: white
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
  language: en
  icon:
    repo: fontawesome/brands/github

# Add this for left alignment
extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/twanglom/pyegro
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/pyegro/

nav:
  - Home: index.md
  - Getting Started:
      - Installation: getting-started/installation.md
      - Quick Start: getting-started/quickstart.md
  - User Guide:
      - Design of Experiment: user-guide/doe.md
      - Efficient Global Optimization: user-guide/ego.md
      - Surrogate Modeling: user-guide/meta.md
      - Robust Optimization: user-guide/robustopt.md
      - Sensitivity Analysis: user-guide/sensitivity.md
      - Uncertainty Quantification: user-guide/uq.md
  - Application Examples:
      - Overview: examples/overview.md
      - DOE Examples: examples/doe-examples.md
      - EGO Examples: examples/ego-examples.md
  - API Reference: api-reference.md


repo_name: twanglom/PyEGRO
repo_url: https://github.com/twanglom/PyEGRO